# Generated by Django 5.2.1 on 2025-05-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="book",
            name="publication_date",
        ),
    ]
