# Generated by Django 5.2.1 on 2025-05-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_remove_book_isbn_remove_book_publication_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
